export const markdownExamples: Record<string, string> = {
  "heading-1": "# Heading Level 1",
  "heading-2": "## Heading Level 2",
  "heading-3": "### Heading Level 3",
  "heading-4": "#### Heading Level 4",
  "heading-5": "##### Heading Level 5",
  "heading-6": "###### Heading Level 6",
  "setext-heading-1": "Heading Level 1\n=============",
  "setext-heading-2": "Heading Level 2\n-------------",
  "bold": "**Bold Text**",
  "italic": "*Italic Text*",
  "bold-italic": "***Bold and Italic***",
  "strikethrough": "~~Strikethrough~~",
  "inline-code": "`inline code`",
  "fenced-code": "```\nGeneric code block\n```",
  "fenced-code-js": "```js\nconsole.log('Hello');\n```",
  "fenced-code-python": "```python\nprint('Hello')\n```",
  "fenced-code-ruby": "```ruby\nputs 'Hello'\n```",
  "fenced-code-sh": "```sh\necho 'Hello'\n```",
  "link-inline": "[Link Text](https://example.com)",
  "link-reference": "[Example][1]\n\n[1]: https://example.com",
  "link-autolink": "<https://example.com>",
  "link-mailto": "<mailto:someone@example.com>",
  "link-with-title": "[Link with Title](https://example.com \"Title\")",
  "image-inline": "![Alt Text](https://example.com/image.png)",
  "image-reference": "![Alt Text][img1]\n\n[img1]: https://example.com/image.png",
  "image-html": "<img src=\"https://example.com/image.png\" alt=\"Alt Text\" />",
  "image-with-title": "![Alt Text](https://example.com/image.png \"Image Title\")",
  "unordered-list": "- Item 1\n- Item 2\n- Item 3",
  "ordered-list": "1. First\n2. Second\n3. Third",
  "nested-unordered-list": "- Item 1\n  - Subitem 1\n  - Subitem 2\n- Item 2",
  "nested-ordered-list": "1. Step 1\n   1. Substep 1\n   2. Substep 2\n2. Step 2",
  "mixed-list": "- Unordered 1\n1. Ordered 1\n- Unordered 2\n2. Ordered 2",
  "task-list-checked": "- [x] Completed task\n- [ ] Incomplete task",
  "task-list-unchecked": "- [ ] Task A\n- [ ] Task B",
  "block-quote": "> This is a blockquote.",
  "nested-blockquote": "> Outer quote\n> > Inner quote",
  "horizontal-rule": "---",
  "table-simple": "| Header 1 | Header 2 |\n| --- | --- |\n| Cell 1 | Cell 2 |",
  "table-aligned": "| Left | Center | Right |\n| :--- | :---: | ---: |\n| A | B | C |",
  "table-complex": "| Name | Age | Occupation |\n| --- | --- | --- |\n| Alice<br>Bob | 30<br>25 | Engineer<br>Designer |",
  "footnote-definition": "Here's a sentence with a footnote.[^1]\n\n[^1]: Footnote content.",
  "footnote-reference": "Use a footnote reference like[^1].",
  "definition-list": "Term 1\n: Definition 1\n\nTerm 2\n: Definition 2",
  "abbreviation": "*[HTML]: HyperText Markup Language",
  "html-comment": "<!-- This is a comment -->",
  "html-raw": "<div class=\"raw-html\">Raw HTML content</div>",
  "html-table": "<table>\n  <tr><td>Cell</td></tr>\n</table>",
  "html-ul": "<ul><li>List Item</li></ul>",
  "html-ol": "<ol><li>List Item</li></ol>",
  "inline-math": "$E=mc^2$",
  "block-math": "$$\n\\int_0^\\infty e^{-x} dx = 1\n$$",
  "emoji-smile": "😄",
  "emoji-heart": "❤️",
  "emoji-star": "⭐",
  "emoji-coffee": "☕",
  "emoji-party": "🎉",
  "emoji-rocket": "🚀",
  "emoji-fire": "🔥",
  "emoji-thumbs-up": "👍",
  "emoji-clap": "👏",
  "emoji-check-mark": "✔️",
  "emoji-cross-mark": "❌",
  "hard-break": "Line one  \nLine two",
  "soft-break": "Line one\nLine two",
  "escape-character": "\\*Not italic*",
  "header-id": "## Heading {#custom-id}",
  "yaml-front-matter": "---\ntitle: Sample\n---",
  "frontmatter-json": "```json\n{\"key\": \"value\"}\n```",
  "admonition-info": ":::info\nInfo block\n:::",
  "admonition-warning": ":::warning\nWarning block\n:::",
  "admonition-tip": ":::tip\nTip block\n:::",
  "admonition-caution": ":::caution\nCaution block\n:::",
  "inserted-text": "++Inserted Text++",
  "deleted-text": "~~Deleted Text~~",
  "superscript": "This is 2^nd^ place",
  "subscript": "H~2~O is water",
  "highlight": "==Highlighted Text==",
  "unicode-character": "Ω α β γ",
  "table-with-colspan": "| A | B |\n| --- | ---: |\n| C | D |",
  "html-entity-amp": "&amp;",
  "html-entity-lt": "&lt;",
  "html-entity-gt": "&gt;",
  "markdown-comment": "[//]: # (This is a markdown comment)",
  "definition-list-term": "Term A",
  "definition-list-definition": ": Definition A",
  "nested-list-after-heading": "### List\n- Item 1\n  - Subitem",
  "list-after-paragraph": "Paragraph text.\n\n- Item 1\n- Item 2",
  "pdf-link": "[PDF](file.pdf)",
  "video-link": "[Video](video.mp4)",
  "audio-link": "[Audio](audio.mp3)",
  "custom-container": ":::custom\nCustom container\n:::",
  "frontmatter-yaml": "---\nlayout: post\n---",
  "math-equation": "`a^2 + b^2 = c^2`",
  "math-expression": "`\\frac{a}{b}`",
  "reference-style-link": "[ref-link][ref]\n\n[ref]: https://ref.com",
  "reference-style-image": "![ref-img][img]\n\n[img]: https://img.com",
  "checkboxes-mixed": "- [x] Done\n- [ ] Not done\n- [x] Done too",
  "mixed-content-block": "> Quote\n\n1. List item\n\n```js\nconsole.log();\n```",
  "list-element-with-html": "- <span>HTML inside list</span>",
  "raw-html-span": "<span style=\"color:red\">Red Text</span>",
  "raw-html-block": "<div>\nBlock HTML\n</div>"
};

export function getMarkdownSnippet(keyword: string): string | undefined {
  return markdownExamples[keyword];
}
